apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: venkyg/node-web-app:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: nodeapp-service
spec:
    type: LoadBalancer
    ports:
    - targetPort: 3000
      port: 80
    selector:
        app: nodeapp