apiVersion: v1
kind: Pod
metadata: 
    name: nodeapp
    labels: 
        app: nodeapp
spec:
    containers:
        - image: venkyg/node-web-app:1.0
          name: nodeapp
          ports:
            - containerPort: 3000